### ISSUE TITLE
SugarBLAS incompatible with system image building

### ISSUE THREAD

**Issue by fguevaravas** [lopezm94/SugarBLAS.jl#3]
There is a problem with precompilation of functions created with the `@blas!` macro in SugarBLAS in both Julia v0.5.2 and 0.6.0. Concretely it gives an undefined variable error `:uv_eventloop` when such a function is included in an userimg. 

I suspect it has to do with using Channels in [Match.jl](https://github.com/lopezm94/SugarBLAS.jl/blob/master/src/Match/Match.jl) as they somehow use libuv, but I wasn't able to track the issue further because I am not familiar with Channels. This bug means that [IterativeSolvers.jl](https://github.com/JuliaMath/IterativeSolvers.jl) cannot be included in a userimg either (in case someone else is having the same problem).

To reproduce create file `uvevent_bug.jl` in the current directory containing:
```julia
using SugarBLAS
function sg_axpy!(a,x,y)
 @blas! y+=a*x
end
```
Then in the REPL
```julia
include(joinpath(JULIA_HOME, Base.DATAROOTDIR, "julia", "build_sysimg.jl"))
build_sysimg(".","native","uvevent_bug.jl")
```
After a long time and lots of output I get the error:
```
/Applications/Julia-0.6.app/Contents/Resources/julia/share/julia/base/precompile.jl
LoadError("sysimg.jl", 408, LoadError("/Applications/Julia-0.6.app/Contents/Resources/julia/share/julia/base/userimg.jl", 31, UndefVarError(:uv_eventloop)))
ERROR: failed process: Process(`/Applications/Julia-0.6.app/Contents/Resources/julia/bin/julia -C native --output-ji ..ji --output-o ..o -J inference.ji --startup-file=no sysimg.jl`, ProcessExited(1)) [1]
Stacktrace:
 [1] pipeline_error(::Base.Process) at ./process.jl:682
 [2] run(::Cmd) at ./process.jl:651
 [3] (::##2#3{Bool,String})() at /Applications/Julia-0.6.app/Contents/Resources/julia/share/julia/build_sysimg.jl:81
 [4] cd(::##2#3{Bool,String}, ::String) at ./file.jl:70
 [5] #build_sysimg#1(::Bool, ::Bool, ::Function, ::String, ::String, ::String) at /Applications/Julia-0.6.app/Contents/Resources/julia/share/julia/build_sysimg.jl:48
 [6] build_sysimg(::String, ::String, ::String) at /Applications/Julia-0.6.app/Contents/Resources/julia/share/julia/build_sysimg.jl:28
```

**Comment by lopezm94** [comment]
Thanks, it should now be solved. May I ask what the sysimg is for?

**Comment by fguevaravas** [comment]
Thanks, I confirm this fixes the problem. I am closing the issue.

The system image is a way of adding modules/packages to the julia environment so that [they are all available in compiled form](https://docs.julialang.org/en/stable/devdocs/sysimg/). In my case I am using [IterativeSolvers.jl](https://github.com/dhoegh/BuildExecutable.jl) in a julia application where the user shouldn't have access to the source code. This can be done by generating a system image and sending it to the user, but it requires a julia install. Instead I am using [BuildExecutable.jl](https://github.com/dhoegh/BuildExecutable.jl) to bundle julia, a system image and the required libraries to get a standalone application that does not require the user to install julia.
